-- ==============================================================================
-- HYPRLAND DEFAULT LUA CONFIGURATION (v0.55+)
-- ==============================================================================
-- This is a translated default config to get you started with Hyprland's new
-- Lua configuration. For full documentation, refer to wiki.hypr.land.

-- Setting this to false removes the yellow "autogenerated" warning at the top
hl.config({ autogenerated = false })


-- ==========================================
-- 1. MONITORS
-- ==========================================
-- Syntax: hl.monitor("name", "resolution", "position", scale)
-- Passing an empty string as the name applies to any unnamed monitor.
hl.monitor("", "highres", "auto", 1)


-- ==========================================
-- 2. MY PROGRAMS & VARIABLES
-- ==========================================
-- Using standard Lua variables makes managing preferred apps incredibly easy
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

local terminal = "kitty"
local fileManager = "thunar"
local menu = "rofi --show drun"
local browser = "google-chrome-stable"


-- ==========================================
-- 3. AUTOSTART
-- ==========================================
-- Executes commands once when Hyprland boots
hl.exec_once("waybar & awww-daemon & swaync & hypridle")
hl.exec_once("wl-paste --type text --watch cliphist store")
hl.exec_once("wl-paste --type image --watch cliphist store")
hl.exec_once("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")


-- ==========================================
-- 4. ENVIRONMENT VARIABLES
-- ==========================================
-- Use hl.env() to set environment variables for your Wayland session
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-- ==========================================
-- 5. LOOK AND FEEL (GENERAL CONFIG)
-- ==========================================
-- In Lua, settings are passed natively via the hl.config table
hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 5,
        border_size = 2,
        
        -- Hex/RGBA values are passed as strings
        ["col.active_border"] = "rgba(33ccffee) rgba(00ff99ee) 45deg",
        ["col.inactive_border"] = "rgba(595959aa)",

        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle"
    },

    decoration = {
        rounding = 5,
        active_opacity = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)"
        },

        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696
        }
    },

    animations = {
        enabled = true,
        -- You can define advanced animation curves here
    },

    dwindle = {
        pseudotile = true, -- Master switch for pseudotiling
        preserve_split = true, -- Keeps split ratio intact when creating new windows
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = 1, -- Set to 0 or 1 to disable the anime mascot
        disable_hyprland_logo = true,
    }
})


-- ==========================================
-- 6. INPUT AND GESTURES
-- ==========================================
hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",

        follow_mouse = 1,
        sensitivity = 0, -- -1.0 to 1.0. 0 means no modification.

        touchpad = {
            natural_scroll = false
        }
    },

    gestures = {
        workspace_swipe = false,
    }
})


-- ==========================================
-- 7. KEYBINDINGS
-- ==========================================
local mod = "SUPER"

-- Core Applications
hl.bind(mod, "RETURN", hl.dsp.exec(terminal), { bypass = true})
hl.bind(mod, "Q", hl.dsp.killactive(), { bypass = true})
hl.bind(mod, "M", hl.dsp.exit(), { bypass = true})
hl.bind(mod, "R", hl.dsp.exec("~/.config/hypr/scripts/launch-waybar.sh"), { bypass = true})
hl.bind(mod, "L", hl.dsp.exec(hyprlock), { bypass = true})
hl.bind(mod, "F", hl.dsp.fullscreen(), { bypass = true})
hl.bind(mod, "SHIT + F", hl.dsp.fullscreen(1), { bypass = true})
hl.bind(mod, "ALT + SPACE", hl.dsp.togglefloating(), { bypass = true})
hl.bind(mod, "J", hl.dsp.togglesplit()) -- dwindle
hl.bind(mod, "SPACE", hl.dsp.exec(menu), { bypass = true})
hl.bind(mod, "E", hl.dsp.exec(fileManager), { bypass = true})
hl.bind(mod, "B", hl.dsp.exec(browser), { bypass = true})
hl.bind(mod, "S", hl.dsp.exec("grim -g "$(slurp)" - | swappy -f -"), { bypass = true})
hl.bind(mod, "O", hl.dsp.exec("~/.config/waybar/scripts/audio-output-toggle.sh"), { bypass = true})
hl.bind(mod, "W", hl.dsp.exec("~/.config/hypr/scripts/wallpaper-selector.sh"), { bypass = true})
hl.bind(mod, "SHIFT + W", hl.dsp.exec("~/.config/hypr/scripts/wallpaper-random.sh"), { bypass = true})
hl.bind(mod, "V", hl.dsp.exec("liphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy"), { bypass = true})
hl.bind(mod, "T", hl.dsp.exec(terminal .. "--class btop-float -e btop"), { bypass = true})
hl.bind(mod, "G", hl.dsp.exec(browser .. ' --app="https://gemini.google.com/app"'), { bypass = true})

-- Move window focus using arrow keys
hl.bind(mod, "left", hl.dsp.movefocus("l"))
hl.bind(mod, "right", hl.dsp.movefocus("r"))
hl.bind(mod, "up", hl.dsp.movefocus("u"))
hl.bind(mod, "down", hl.dsp.movefocus("d"))

-- Workspaces 1-9 (Using a Lua loop to keep the config clean!)
for i = 1, 9 do
    -- Switch to workspace
    hl.bind(mod, tostring(i), hl.dsp.workspace(tostring(i)), { bypass = true})
    -- Move active window to workspace
    hl.bind(mod .. "_SHIFT", tostring(i), hl.dsp.movetoworkspace(tostring(i)), { bypass = true})
end


-- Scroll through existing workspaces with mouse scroll
hl.bind(mod, "mouse_down", hl.dsp.workspace("e+1"), { bypass = true})
hl.bind(mod, "mouse_up", hl.dsp.workspace("e-1"), { bypass = true})

-- Move/resize windows with main mod + mouse drag
hl.bind(mod, "mouse:272", hl.dsp.movewindow())
hl.bind(mod, "mouse:273", hl.dsp.resizewindow())

-- Media & Volume Controls (Using the options table for repeat behavior)
hl.bind("", "XF86AudioRaiseVolume", hl.dsp.exec("~/.config/hypr/scripts/volume-notify.sh up"), { bypass = true, ["repeat"] = true })
hl.bind("", "XF86AudioLowerVolume", hl.dsp.exec("~/.config/hypr/scripts/volume-notify.sh down"), { bypass = true, ["repeat"] = true })
hl.bind("", "XF86AudioMute", hl.dsp.exec("~/.config/hypr/scripts/volume-notify.sh mute"), { bypass = true })
hl.bind("", "XF86MonBrightnessUp", hl.dsp.exec("~/.config/hypr/scripts/brightness-notify.sh up"), { bypass = true, ["repeat"] = true })
hl.bind("", "XF86MonBrightnessDown", hl.dsp.exec("~/.config/hypr/scripts/brightness-notify.sh down"), { bypass = true, ["repeat"] = true })
hl.bind("", "XF86AudioNext", hl.dsp.exec("playerctl next"), { bypass = true })
hl.bind("", "XF86AudioPause", hl.dsp.exec("playerctl play-pause"), { bypass = true })
hl.bind("", "XF86AudioPlay", hl.dsp.exec("playerctl play-pause"), { bypass = true })
hl.bind("", "XF86AudioPrev", hl.dsp.exec("playerctl previous"), { bypass = true })

-- ==========================================
-- 8. WINDOW AND WORKSPACE RULES
-- ==========================================
-- hl.windowrule(rule, window_selector)
hl.windowrule("float", "^(pavucontrol)$")

hl.windowrule("noblur", "^(google-chrome-stable)$")

hl.windowrule("float", "class:^(btop-float)$")
hl.windowrule("size 1200 800", "class:^(btop-float)$")
hl.windowrule("center", "class:^(btop-float)$")

hl.windowrule("float", "class:^(nmtui-floating)$")
hl.windowrule("size 600 500", "class:^(nmtui-floating)$")
hl.windowrule("center", "class:^(nmtui-floating)$")

hl.windowrule("float", "class:^(org\.pulseaudio\.pavucontrol)$")
hl.windowrule("size 800 700", "class:^(org\.pulseaudio\.pavucontrol)$")
hl.windowrule("center", "class:^(org\.pulseaudio\.pavucontrol)$")

hl.windowrule("float", "class:^(blueman-manager)$")
hl.windowrule("size 800 700", "class:^(blueman-manager)$")
hl.windowrule("center", "class:^(blueman-manager)$")

-- Example: Suppress maximize requests on all apps to mimic classic behavior
hl.windowrule("suppressevent maximize", "class:.*")
